name: Build

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main, ls-integration ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        runtime: [ linux, windows ]
        include:
          - runtime: linux
            os: ubuntu-latest
            setupCmd: ./src/test/resources/ci/scripts/setup.sh
            execCmd: ./src/test/resources/ci/scripts/run.sh
            reportName: linux-test-report
          - runtime: windows
            os: windows-latest
            setupCmd: bash ./src/test/resources/ci/scripts/setup.sh
            execCmd: bash ./src/test/resources/ci/scripts/run.sh
            reportName: windows-test-report
    steps:
      - name: 'Checkout liberty-tools-intellij'
        uses: actions/checkout@v3
        with:
          path: liberty-tools-intellij
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      - name: 'Install required integration test software'
        working-directory: ./liberty-tools-intellij
        run: ${{ matrix.setupCmd }}
      - name: 'Run UI integration tests'
        working-directory: ./liberty-tools-intellij
        run: ${{ matrix.execCmd }}
      - name: 'Archive Test logs and reports'
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.reportName }}
          path: |
            liberty-tools-intellij/build/reports/
      - name: 'Build Liberty-Tools-Intellij'
        working-directory: ./liberty-tools-intellij
        run: bash ./gradlew buildPlugin --info
      - name: 'Archive artifacts'
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: liberty-tools-intellij-${{ github.sha }}
          path: |
            ./**/*liberty-tools-intellij*.zip
            ./**/libs/*liberty-tools-intellij*.jar
          if-no-files-found: warn
          retention-days: 7